function s = createPropertiesStructure()

s = struct('number', nan, ...
    'durationBase', nan, ...
    'durationZero', nan, ...
    'durationTent', nan,  ...
    'durationHalfBase', nan, ...
    'durationHalfZero', nan,...
    'interBlinkMaxAmp', nan, ...
    'interBlinkMaxVelBase', nan, ...
    'interBlinkMaxVelZero', nan, ...
    'negAmpVelRatioBase', nan, ...
    'posAmpVelRatioBase', nan, ...
    'negAmpVelRatioZero', nan, ...
    'posAmpVelRatioZero', nan, ...
    'negAmpVelRatioTent', nan, ...
    'posAmpVelRatioTent', nan, ...
    'timeShutBase', nan, ...
    'timeShutZero', nan, ...
    'timeShutTent', nan, ...
    'closingTimeZero', nan, ...
    'reopeningTimeZero', nan, ...
    'closingTimeTent', nan, ...
    'reopeningTimeTent', nan, ...
    'peakTimeBlink', nan,  ...
    'peakTimeTent', nan,  ...
    'peakMaxBlink', nan, ...
    'peakMaxTent', nan);