function s = createBlinksStructure()
% Return an empty blink structure
s  = struct('fileName', NaN, ...
            'srate', NaN, ...
            'subjectID', NaN, ...
            'experiment', NaN, ...
            'uniqueName', NaN, ...
            'task', NaN, ...
            'startTime', NaN, ...
            'type', NaN, ...
            'signalIndices', NaN, ...
            'candidateSignals', NaN, ...
            'signalInfo', NaN, ...
            'blinkPositions', NaN, ...
            'numberBlinks', NaN, ...
            'goodBlinks', NaN, ...
            'blinkAmpRatios', NaN, ...
            'cutoff', NaN, ...
            'bestMedian', NaN, ...
            'bestRobustStd', NaN, ...
            'goodRatios', NaN, ...  
            'usedSignal', NaN, ...
            'status', NaN);