function [dataHeaders, d] = getSummaryHeaders()
%% Return data headers and structure of positions for blink summaries
dataHeaders = {'badMask', 'leftBaseTime', 'leftZeroTime', 'maxTime', ...
               'rightZeroTime', 'rightBaseTime', ...
               'blinkDuration', 'tentDuration', ...
               'baseHalfDuration', 'zeroHalfDuration', ...
               'pAVRZero', 'pAVRTent', 'pAVRBase', ...
               'nAVRZero', 'nAVRTent', 'nAVRBase'};
d = struct( ...
     'BADMASK', 1, ...
     'LEFTBASE', 2, ...
     'LEFTZERO', 3, ...
     'MAXTIME', 4, ...
     'RIGHTZERO', 5, ...
     'RIGHTBASE', 6, ...
     'ZERODUR', 7, ...
     'TENTDUR', 8, ...
     'BASEHALFDUR', 9, ...
     'ZEROHALFDUR', 10, ...
     'pAVRZERO', 11, ...
     'pAVRTENT', 12, ...
     'pAVRBASE', 13, ...
     'nAVRZERO', 14, ...
     'nAVRTENT', 15, ...
     'nAVRBASE', 16);
end

