function [dataHeaders, d] = getSummaryHeaders()
%% Return data headers and structure of positions for blink summaries
dataHeaders = {'badMask', 'leftBaseTime', 'leftZeroTime', 'maxTime', ...
               'rightZeroTime', 'rightBaseTime', ...
               'durationZero', 'durationBase', 'durationTent', ...
               'durationHalfZero', 'durationHalfBase', ...
               'pAVRZero', 'pAVRTent', 'pAVRBase', ...
               'nAVRZero', 'nAVRTent', 'nAVRBase'};
d = struct( ...
     'BADMASK', 1, ...
     'LEFTBASE', 2, ...
     'LEFTZERO', 3, ...
     'MAXTIME', 4, ...
     'RIGHTZERO', 5, ...
     'RIGHTBASE', 6, ...
     'DURZERO', 7, ...
     'DURBASE', 8, ...
     'DURTENT', 9, ...
     'DURHALFZERO', 10, ...
     'DURHALFBASE', 11, ...
     'pAVRZERO', 12, ...
     'pAVRTENT', 13, ...
     'pAVRBASE', 14, ...
     'nAVRZERO', 15, ...
     'nAVRTENT', 16, ...
     'nAVRBASE', 17);
end

